[package]
name = "iptables-exporter"
version = "0.1.0"
authors = ["Maxim Baz"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.9.0"
clap = "2.33.3"
